### ISSUE TITLE
Documentation states that AF_Packet needs root, users should use capabilities instead

### ISSUE THREAD

**Issue by mpurzynski** [bro/bro-plugins#13]
/sbin/setcap cap_net_raw+eip /opt/bro/bin/bro

Is enough to have Bro working with af_packet as an unprivileged user. That's how I have it running here.

The kernel sources can be a source of truth as well:

net/packet/af_packet.c +2808 (3.19)

    if (!ns_capable(net->user_ns, CAP_NET_RAW))
        return -EPERM;

**Comment by mpurzynski** [comment]
https://github.com/bro/bro-plugins/pull/14

**Comment by 0xxon** [comment]
Thank you, this is merged.
