### ISSUE TITLE
af_packet fatal error: bro-config.h: No such file or directory

### ISSUE THREAD

**Issue by kevross33** [bro/bro-plugins#23]
Hi,

I want to use this as I already have suricata using it and PF_RING + Bro I seem to have issues with when jumping kernels but this should make it easier for me.
 Built with this (never got past make):

./configure --bro-dist=/usr/src/bro-2.4.1
make
make install

Scanning dependencies of target Bro-AF_Packet.linux-x86_64
make[3]: Leaving directory `/usr/src/bro-2.4.1/af_packet/build'
make[3]: Entering directory `/usr/src/bro-2.4.1/af_packet/build'
[ 40%] Building CXX object CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/src/Plugin.cc.o
[ 50%] Building CXX object CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/src/AF_Packet.cc.o
/usr/src/bro-2.4.1/af_packet/src/AF_Packet.cc:2:24: fatal error: bro-config.h: No such file or directory
 #include "bro-config.h"
                        ^
compilation terminated.
make[3]: *** [CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/src/AF_Packet.cc.o] Error 1
make[3]: Leaving directory `/usr/src/bro-2.4.1/af_packet/build'
make[2]: *** [CMakeFiles/Bro-AF_Packet.linux-x86_64.dir/all] Error 2
make[2]: Leaving directory `/usr/src/bro-2.4.1/af_packet/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/bro-2.4.1/af_packet/build'
make: *** [build-it] Error 2

Also when (not if hopefully) this is successfully installed would i be able to enable af_packet in my node configuration file under lb_method?

**Comment by 0xxon** [comment]
Between Bro 2.4.1 and the current master, the name in config.h changed to bro-config.h.

If you want to compile the plugin against 2.4.1, change the include to just #include "config.h" (or just use the state of bro-plugins as it is shipped with 2.4.1, if this plugin is already part of it).
