### ISSUE TITLE
Myricom Plugin Will not Compile

### ISSUE THREAD

**Issue by rvictory** [bro/bro-plugins#24]
I am attempting to compile the Myricom plugin against Bro 2.4 and 2.4.1, no luck on either:

make[3]: Entering directory '/root/bro-plugins/myricom/build'
[ 40%] Building CXX object CMakeFiles/Bro-Myricom.linux-x86_64.dir/src/Myricom.cc.o
/root/bro-plugins/myricom/src/Myricom.cc:1:24: fatal error: bro-config.h: No such file or directory
compilation terminated.
CMakeFiles/Bro-Myricom.linux-x86_64.dir/build.make:104: recipe for target 'CMakeFiles/Bro-Myricom.linux-x86_64.dir/src/Myricom.cc.o' failed
make[3]: *** [CMakeFiles/Bro-Myricom.linux-x86_64.dir/src/Myricom.cc.o] Error 1
make[3]: Leaving directory '/root/bro-plugins/myricom/build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Bro-Myricom.linux-x86_64.dir/all' failed
make[2]: *** [CMakeFiles/Bro-Myricom.linux-x86_64.dir/all] Error 2
make[2]: Leaving directory '/root/bro-plugins/myricom/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/bro-plugins/myricom/build'
Makefile:11: recipe for target 'build-it' failed
make: *** [build-it] Error 2

I have tried changing the #include statement for "bro-config.h" to #include "config.h" as suggested in some other issues (namely the ElasticSearch plugin build issues) with no luck. Here is my configure command line:

./configure --with-myricom=/opt/snf/ --bro-dist=/root/bro-2.4/

Where the Myricom SNF library is in /opt/snf and /root/bro-2.4/ is the bro source directory. Anybody else have this issue or have any solutions?

**Comment by sethhall** [comment]
I just pushed some changes to the Myricom plugin and one thing the changes do is make Bro compile against Bro's git/master branch which is the problem you were encountering.
