### ISSUE TITLE
tcprs compilation error

### ISSUE THREAD

**Issue by ryu80** [bro/bro-plugins#29]
Hello,
i'm trying to compile tcprs but after issuing "make" it shows these error messages :

opt/bro-plugins/tcprs/src/Plugin.cc: In member function 'virtual plugin::Configuration plugin::Bro_TCPRS::Plugin::Configure()':
/opt/bro-plugins/tcprs/src/Plugin.cc:20:13: error: 'HOOK_SETUP_ANALYZER_TREE' was not declared in this scope
  EnableHook(HOOK_SETUP_ANALYZER_TREE, 1);
             ^
CMakeFiles/Bro-TCPRS.linux-x86_64.dir/build.make:84: recipe for target 'CMakeFiles/Bro-TCPRS.linux-x86_64.dir/src/Plugin.cc.o' failed
make[3]: *** [CMakeFiles/Bro-TCPRS.linux-x86_64.dir/src/Plugin.cc.o] Error 1
make[3]: Leaving directory '/opt/bro-plugins/tcprs/build'
CMakeFiles/Makefile2:66: recipe for target 'CMakeFiles/Bro-TCPRS.linux-x86_64.dir/all' failed
make[2]: *** [CMakeFiles/Bro-TCPRS.linux-x86_64.dir/all] Error 2
make[2]: Leaving directory '/opt/bro-plugins/tcprs/build'
Makefile:117: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/bro-plugins/tcprs/build'
Makefile:11: recipe for target 'build-it' failed
make: *** [build-it] Error 2

am i doing something wrong?

**Comment by jswaro** [comment]
Sounds like either someone removed the hook from the main bro repository,
or you may not have updated a recent enough version of bro's development
branch to have the hook.

Can you provide the git hash of both repos?

James Swaro

**Comment by ryu80** [comment]
thanks for reply
the bro is compiled today from the last package available.

is this the git output requested for the repo?

root@debian:/opt/bro-plugins/tcprs# git ls-remote git://git.bro.org/bro-plugins.git
ebab672fa404b26944a6df6fbfb1aaab95ec5d48	HEAD
52bf3c8580eea028e7e3aaf7f15f2b7424d1e674	refs/heads/fastpath
ebab672fa404b26944a6df6fbfb1aaab95ec5d48	refs/heads/master
dc75d964f59fe172b6b3051e65f9d1aa788309a9	refs/heads/topic/dnthayer/doc-improvements-2.4
dfd5f057b5960dfdd3d4ab2b8d81085fca58b70a	refs/heads/topic/dnthayer/fix-typos
a4f21b3f44818564cf4c46abd2e63593c49b08f5	refs/heads/topic/dnthayer/ticket1536
98cd189cf22dbda4459722a8c6f5993f23668ef1	refs/heads/topic/johanna/postgres
6b6f1839690ce9f8c8824b39ce30ff7cbcd3b989	refs/heads/topic/robin/netmap
9072e28935ba85b6938fe946d7aa23cb58ee1566	refs/heads/topic/robin/plugin-updates
98ad8a5b97f601a3ec9a773d87582438212b8290	refs/heads/topic/robin/rework-packets-merge
c34f3280d4d7722fc1060898b7a3dd415fa5f2dc	refs/heads/topic/robin/tcprs-merge
6e078352fdd22b0b4ce8a98112c9c52ab30a0271	refs/heads/topic/robin/tcprs-merge-again
390be69cf8fc0e8834820afa6b61f5706c2ca173	refs/heads/topic/vladg/es-fixes
52bf3c8580eea028e7e3aaf7f15f2b7424d1e674	refs/remotes/github/fastpath
ebab672fa404b26944a6df6fbfb1aaab95ec5d48	refs/remotes/github/master
dc75d964f59fe172b6b3051e65f9d1aa788309a9	refs/remotes/github/topic/dnthayer/doc-improvements-2.4
dfd5f057b5960dfdd3d4ab2b8d81085fca58b70a	refs/remotes/github/topic/dnthayer/fix-typos
a4f21b3f44818564cf4c46abd2e63593c49b08f5	refs/remotes/github/topic/dnthayer/ticket1536
98cd189cf22dbda4459722a8c6f5993f23668ef1	refs/remotes/github/topic/johanna/postgres
6b6f1839690ce9f8c8824b39ce30ff7cbcd3b989	refs/remotes/github/topic/robin/netmap
9072e28935ba85b6938fe946d7aa23cb58ee1566	refs/remotes/github/topic/robin/plugin-updates
98ad8a5b97f601a3ec9a773d87582438212b8290	refs/remotes/github/topic/robin/rework-packets-merge
c34f3280d4d7722fc1060898b7a3dd415fa5f2dc	refs/remotes/github/topic/robin/tcprs-merge
6e078352fdd22b0b4ce8a98112c9c52ab30a0271	refs/remotes/github/topic/robin/tcprs-merge-again
390be69cf8fc0e8834820afa6b61f5706c2ca173	refs/remotes/github/topic/vladg/es-fixes
3df6564178125abe3372c6fd5dd532dd7ec9c40a	refs/tags/release
99d7519991b41a970809a99433ea9c7df42e9d93	refs/tags/release^{}
fb2699066ede2631921f22c342984d6356028d48	refs/tags/v0.1
e1ea9f67cfe3d6a81e0c1479ced0b9aa73e77c87	refs/tags/v0.1^{}
0bc36433fa88c3f2f8291e25918a9af31bae57c5	refs/tags/v0.2
99d7519991b41a970809a99433ea9c7df42e9d93	refs/tags/v0.2^{}

**Comment by jswaro** [comment]
For some reason, this response didn't make it to my email. What does HEAD on your bro repo (not bro-plugins) point to?

**Comment by jswaro** [comment]
The following should be sufficient. Run this in your bro repo 
```Bash
git log --oneline | head -n1
```

**Comment by ryu80** [comment]
here the output
root@debian:/opt/bro-plugins/tcprs# git log --oneline | head -n1
ebab672 Merge remote-tracking branch 'origin/fastpath'

**Comment by jswaro** [comment]
I need the output from your 'bro' repository, not bro-plugins.

**Comment by jswaro** [comment]
I'll be more concise. 

I need to know the head of both the 'bro' and 'bro-plugins' repository to diagnose your issue. You've given me the hash from bro-plugins, which tells me that you have the most recent version of 'bro-plugins'. However, I still know nothing about the 'bro' main repository. This is relevant because modifications were made to the 'bro' code base to introduce the hook that the compilation indicates to be 'not found'. If this doesn't make sense, please let me know.

**Comment by jswaro** [comment]
I just built tcprs from the HEAD of both repo's master. I'd like to close this as works-for-me. I'll be happy to help you diagnose your issue, but it doesn't appear to be an issue with the repositories. 

```
jswaro@ds9 ~/git/bro-plugins $ git log --oneline | head -n1
ebab672 Merge remote-tracking branch 'origin/fastpath'

jswaro@ds9 ~/git/bro $ git log --oneline | head -n1
72903c8 Add new ciphers from RFC 7905.
```

**Comment by jswaro** [comment]
@rsmmr 

Would you mind closing this bug if it goes untouched for a few days?

**Comment by 0xxon** [comment]
Will do.

Johanna

**Comment by jswaro** [comment]
Thanks
