### ISSUE TITLE
pfring::multi does not distribute well

### ISSUE THREAD

**Issue by alonbg** [bro/bro-plugins#30]
eth4/5 - rx,
eth6/7 -tx

11 bro worker instances cluster
lb_mode=pf_ring
interface='pf_ring::multi:eth4;eth5;eth6;eth7'
or
interface='pf_ring::eth4,eth5,eth6,eth7'
log lines are written 11 fold (number of worker instances) to the log (e.g. in conn.log or http.log)
Had to fallback to bonding interface=bond0 where (ifenslave bond0 eth4 eth5 eth6 eth7)

**Comment by sethhall** [comment]
Is this a bug in the pfring plugin or a bug in pfring?  If you setup everything correctly with pfring and load balance merged ports out to tcpdump, do you get duplicate traffic?

**Comment by alonbg** [comment]
Does not duplication with tcpdump.
Also, with bro cluster it duplicates with the interface pf_ring::bond0  (where `ifenslave bond0 eth4 eth5 eth6 eth7')

**Comment by sethhall** [comment]
Have you tried using the PF_Ring libpcap wrapper instead of the plugin?  If you use the pf_ring libpcap wrapper, I suppose you'd be able to specify the interface in node.cfg like this...

multi:eth4;eth5;eth6;eth7

**Comment by alonbg** [comment]
I'm using pf_ring libcap wrapper. I tested your suggestion - multipe interface names without the pf_ring:: plugin prefix.
In which case _multi:_ supports up to two interfaces (i.e. `bro -i multi:eth3;eth4`)

Otherwise:
fatal error: problem with interface multi:eth3;eth4;eth5 (pcap_error: No such device exists (pcap_activate))

And without _multi_ up to three interfaces (i.e. `bro -i  eth3,eth4,eth5`)

Otherwise:
fatal error: problem with interface eth3,eth4,eth5,eth6 (pcap_error: No such device exists (pcap_activate))

**Comment by alonbg** [comment]
OK, the fact that it did not work with more than 2,3 interfaces was probably due to unproper escape sequencing ( I also updated to latest pf_ring and bro)

With a single bro it works (e.g. I see http.log)
That is with either `bro -i 'multi:eth4;eth5;eth6;eth7 ...'` or with `bro -i 'eth4,eth5,eth6,eth7 ...'`

Never the less  in a cluster mode (etc/node.cfg) I see no <protocol-x>.log files at all.
interface='multi:eth4;eth5;eth6;eth7 ...'
-- or --
interface='eth4,eth5,eth6,eth7 ...'

**Comment by sethhall** [comment]
I don't view this as a problem with any of the Bro plugins.  If there is some better behavior, that would be an issue to address in Broctl or just solve your problem in a different way.
