### ISSUE TITLE
Migrate to bro-pkg

### ISSUE THREAD

**Issue by JonZeolla** [bro/bro-plugins#40]
Please migrate these plugins to be bro-pkg managed.

**Comment by rsmmr** [comment]
Yep, that's on the near-term to do list, we'll get that started soon.

**Comment by sethhall** [comment]
I closed this ticket since it's a major goal, not a task.

**Comment by JonZeolla** [comment]
Also, as a note, I am working on migrating the kafka plugin to be a bro-pkg.
