### ISSUE TITLE
plugin syntax does not work on centos 6

### ISSUE THREAD

**Issue by trixpan** [bro/bro-plugins#46]
` nn.interface="{:s}:{:d}".format(orig_if, interface_pipes[nn.host,orig_if])`

triggers a `python zero length field name in format` error

**Comment by trixpan** [comment]
using 
`nn.interface="{0}:{1}".format(orig_if, interface_pipes[nn.host,orig_if])`

seems to do the trick but I am not sure if this is supported on modern python

**Comment by sethhall** [comment]
Fixed.
