### ISSUE TITLE
ElasticSearch plugin not compiling

### ISSUE THREAD

**Issue by evoxco** [bro/bro-plugins#7]
Running against 2.4.1 bro source

make[3]: Leaving directory `/home/nsm/bro-plugins/elasticsearch/build'
make[3]: Entering directory `/home/nsm/bro-plugins/elasticsearch/build'
[ 44%] Building CXX object CMakeFiles/Bro-ElasticSearch.linux-x86_64.dir/src/ElasticSearch.cc.o
/home/nsm/bro-plugins/elasticsearch/src/ElasticSearch.cc:7:24: fatal error: bro-config.h: No such file or directory
 #include "bro-config.h"
                        ^
compilation terminated.

**Comment by 0xxon** [comment]
There have been changes to the bro build system in master versus 2.4(.1) that prevent straightforward building of newer plugins with master.

Is there any reason you cannot just build the easticsearch plugin that comes with 2.4.1? It should be in the directory aux/plugins/elasticsearch. Alternatively, you can also checkout tag v0.2 of this repository - https://github.com/bro/bro-plugins/releases/tag/v0.2 

If for some reason this is not an option, reverting 9abf68366e91eaf5a30c82930a4e906006d6eea9 should allow you to compile bro-plugins against 2.4.1

**Comment by evoxco** [comment]
I was trying out 2.4.1 and I couldn't find the aux/plugins/elasticsearch on the same (aux/plugin is empty). This is the main reason I used the current bro-plugins. 
I manually removed bro-config.h and compiled and works fine now. No issues 
Thank you
